---
- name: Configure webserver with nginx
  hosts: webservers
  become: true
  tasks:
    - name: Ensure nginx is installed
      package:
        name: nginx
        state: present
        update_cache: yes

    - name: Create nginx config directory
      file:
        path: /etc/nginx/sites-available
        state: directory
        mode: '0755'
      become: yes

    - name: Copy nginx config file
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default
      become: yes

    - name: Ensure sites-enabled directory exists
      file:
        path: /etc/nginx/sites-enabled
        state: directory
        mode: '0755'
      become: yes

    - name: Enable configuration
      command: "/bin/bash -c 'if [ ! -e /etc/nginx/sites-enabled/default ];\
                then ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default; fi'"
      become: yes


 
    - name: Copy index.html
      template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html
      become: yes

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
      become: yes

